"""add primary admin flag

Revision ID: 2b89d1ab7187
Revises: e6b5e29cc922
Create Date: 2026-09-26 18:57:53.936435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b89d1ab7187'
down_revision: Union[str, Sequence[str], None] = 'e6b5e29cc922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column(
        'is_primary_admin',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_primary_admin')
    # ### end Alembic commands ###
