"""add phone to patient and doctor

Revision ID: 710d9569a426
Revises: cc73cdc2a4f0
Create Date: 2026-09-20 12:07:40.069928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710d9569a426'
down_revision: Union[str, Sequence[str], None] = 'cc73cdc2a4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'email')
    op.drop_column('patients', 'phone')
    op.drop_column('doctors', 'phone')
    # ### end Alembic commands ###
