"""add email to doctor

Revision ID: cc73cdc2a4f0
Revises: 31768dc8130a
Create Date: 2026-09-20 11:56:10.546319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc73cdc2a4f0'
down_revision: Union[str, Sequence[str], None] = '31768dc8130a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'email')
    # ### end Alembic commands ###
